import Work1 from "../../assets/work1.jpg";
import Work2 from "../../assets/Chat-app.png";
import Work3 from "../../assets/work3.jpg";
import Work4 from "../../assets/DCStock.png";
import Work6 from "../../assets/work6.jpg";
import Work7 from "../../assets/work7.jpg";
import Work9 from "../../assets/work9.jpg";
import Work10 from "../../assets/work10.jpg";
import Work11 from "../../assets/work11.png";
import Work12 from "../../assets/twitter-clone.png";
import work5 from "../../assets/carePulse-img.png";

export const projectsData = [
  {
    id: 1,
    image: Work4,
    title: "DCStock App",
    link: "https://main.d2va3tidas9dgb.amplifyapp.com/dashboard",
    tools: [
      "HTML",
      "CSS",
      "TypeScript",
      "Tailwind Css",
      "NextJs",
      "Redux Toolkit",
      "Lucide React",
      "Recharts",
      "NodeJs",
      "Express",
      "Prisma",
      "PostgreSQL",
      "AWS",
    ],
    category: "web",
  },
  {
    id: 1,
    image: work5,
    title: "carePulse App",
    link: "https://carepulse-app.vercel.app/",
    tools: [
      "HTML",
      "CSS",
      "TypeScript",
      "Tailwind Css",
      "NextJs",
      "Appwrite",
      "Twilio",
      "ShadCn/ui",
      "Zod",
      "Clsx",
      "React dropzone",
      "React Hook Form",
      "Sentry",
    ],
    category: "web",
  },
  {
    id: 2,
    image: Work12,
    title: "Twitter Clone App",
    link: "https://twitter-clone-yb4p.onrender.com",
    tools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind Css",
      "react",
      "NodeJs",
      "Express",
      "MongoDB",
      "Mongoose",
      "Cloudinary",
      "React Query",
    ],
    category: "web",
  },
  {
    id: 3,
    image: Work2,
    title: "Chat App",
    link: "https://chat-app-5ivw.onrender.com/",
    tools: [
      "HTML",
      "CSS",
      "TypeScript",
      "Tailwind Css",
      "react",
      "Prisma",
      "Postgresql",
      "Zustand",
      "Node Js",
      "Express js",
      "Jsonwebtoken",
      "Socket.io",
      "react-router-dom",
    ],
    category: "web",
  },
  {
    id: 4,
    image: Work11,
    title: "Apple iPhone Page",
    link: "https://apple-web-site.netlify.app/",
    tools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind Css",
      "react",
      "Three.js",
      "Gsap",
    ],
    category: "web",
  },
  {
    id: 5,
    image: Work10,
    title: "Countries App",
    link: "https://countriesapplication.netlify.app/",
    tools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind Css",
      "react",
      "React-router-dom",
    ],
    category: "web",
  },
  {
    id: 6,
    image: Work9,
    title: "Shopi E-commerce",
    link: "https://main--shopping-app-project.netlify.app/",
    tools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind Css",
      "react",
      "React-router-dom",
    ],
    category: "web",
  },
  {
    id: 7,
    image: Work6,
    title: "Manage Landing Page",
    link: "https://main--manage-page-proyect.netlify.app/",
    tools: ["HTML", "CSS", "JavaScript", "TailWind Css", "react"],
    category: "web",
  },
  {
    id: 8,
    image: Work7,
    title: "Nike Landing Page",
    link: "https://main--calm-muffin-700a5e.netlify.app/#contact-us",
    tools: ["HTML", "CSS", "JavaScript", "TailWind Css", "react"],
    category: "web",
  },
  {
    id: 9,
    image: Work1,
    title: "Space Tourism Page",
    link: "https://tourism-space-page.netlify.app",
    tools: [
      "HTML",
      "CSS",
      "JavaScript",
      "Styled Components",
      "react",
      "React-router-dom",
    ],
    category: "web",
  },

  {
    id: 10,
    image: Work3,
    title: "Modern UI Site",
    link: "https://modernuisite.netlify.app",
    tools: ["HTML", "CSS", "JavaScript", "react", "React-icons"],
    category: "design",
  },
];

export const projectsNav = [
  { name: "all" },
  { name: "web" },
  { name: "app" },
  { name: "design" },
];
